### ISSUE TITLE
[FEATURE] Less verbose output

### ISSUE THREAD

**Issue by muchgitsuchwow** [oknozor/toml-bombadil#102]
**Is your feature request related to a problem? Please describe.**
Current output feels like a verbose one. With a bigger list of dotfiles errors might get missed too easily.

**Describe the solution you'd like**
I'd love to have the default output just throw out changes and errors while the current behavior becomes available using a `--verbose` switch.

**Comment by oknozor** [comment]
> I'd love to have the default output just throw out changes and errors 

this is now the default behavior
