### ISSUE TITLE
[BUG] User unfriendly behavior running bombadil install

### ISSUE THREAD

**Issue by svenstaro** [oknozor/toml-bombadil#106]
**Describe the bug**
Running `bombadil install` without argument results in
```
bombadil install
No such file or directory (os error 2)
```
and critically it also deletes the pre-existing symlink at `.config/bombadil.toml`.

**To Reproduce**
Just run `bombadil install` in your home dir.

**Expected behavior**
I don't really know. What is it even supposed to do without argument? Anyway, it should NOT delete the pre-existing symlink at `.config/bombadil.toml`. It should also provide a more helpful error message.

**Additional context**
`--help` doesn't document how `install` can work without being called with an explicit dotfiles directory.

**Comment by oknozor** [comment]
Without arguments it will look for a `bombadil.toml` file in the current directory. 
This should indeed just print an error and abort if the file is not found.
