### ISSUE TITLE
[BUG] Non-existant variables result in variable expression being rendered verbatim

### ISSUE THREAD

**Issue by svenstaro** [oknozor/toml-bombadil#107]
**Describe the bug**
In case a variable `a` isn't set, the expression `{{a}}` will not result in an error but it will just be rendered verbatim. It should instead produce an error. Silent failures aren't good! Perhaps an option should instead be provided to ignore errors but the errors should be visible by default.

**To Reproduce**
Have a config with `{{a}}` but don't define that variable.

**Expected behavior**
It should result in an error during `bombadil link` since the variable is unset and will likely result in the unexpected behavior of the expression `{{a}}` being rendered verbatim.

**Comment by oknozor** [comment]
I made a quick fix, but I think we need to add proper error handling with thiserror
