### ISSUE TITLE
[FEATURE] Add bombadil watch to automatically sync configs on changes

### ISSUE THREAD

**Issue by svenstaro** [oknozor/toml-bombadil#112]
**Is your feature request related to a problem? Please describe.**
Currently the default bombadil process is a bit annoying as on every config change, you have to remember to type `bombadil link -p stuff`. 

**Describe the solution you'd like**
It would be nice for rapid config changes to be able to do just `bombadil watch -p stuff` and it would detect changes automatically on the dotfiles dir and then run `bombadil link -p stuff`. I think this would be easy to do when using watchexec as a lib.

**Comment by oknozor** [comment]
That's a great idea ! 
Do you want to work on this @svenstaro ?

**Comment by svenstaro** [comment]
Sure, can do.

**Comment by theowenyoung** [comment]
@oknozor @svenstaro Hi, it seems watch feature is finished, but there is no docs for it?
