### ISSUE TITLE
[BUG] Can not install, unresolved import `watchexec::ignore`

### ISSUE THREAD

**Issue by theowenyoung** [oknozor/toml-bombadil#139]
**Describe the bug**

`cargo install toml-bombadil`

```
error[E0432]: unresolved import `watchexec::ignore`
   --> /Users/green/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-bombadil-3.1.0/src/lib.rs:224:13
    |
224 |             ignore,
    |             ^^^^^^ no `ignore` in the root
```

**To Reproduce**
`cargo install toml-bombadil`

**Additional context**

I tried the stable rust and nightly rust, they all throw this error.

**Comment by theowenyoung** [comment]
yes, I'm on macOS, and when I try to compile from source, it works. 

Ok, if it was not designed to macOS, maybe I should check the other tool, like <https://github.com/comtrya/comtrya>  , <https://github.com/rash-sh/rash>

Thanks for you great job!

**Comment by oknozor** [comment]
That said there is no reason it won't work on any unix like os. I'd be curious to have some feedback from macos users.

**Comment by oknozor** [comment]
This is not released yet but should be fixed in the main branch
