### ISSUE TITLE
[FEATURE] Preserve existing dotfiles

### ISSUE THREAD

**Issue by all64bits** [oknozor/toml-bombadil#142]
**Is your feature request related to a problem? Please describe.**

It would be ideal if an installation of bombadil dotfiles could be completely reversible. Currently if there is an existing hard link file eg ~/.someapp.cfg, and you have your own version in your dotfiles repo, eg bombadil-dir/someapp.cfg, "bombadil link" will clobber the existing file.

**Describe the solution you'd like**

If bombadil finds an existing file in place of where it wants to deploy a symlink, it saves a copy of the file to bombadil-dir/.dots/previous_state_files/. When running "bombadil unlink", this will restore any saved hard link dotfiles to their original location.

**Describe alternatives you've considered**

Alternative is the existing functionality. Not a huge issue, but the above feature would be a nicety.

**Additional context**

**Comment by oknozor** [comment]
I think this is beyond the scope of a dotfile manager. You probably want to use git along with tom-bombadil do to this.
