### ISSUE TITLE
Add unlink command

### ISSUE THREAD

**Issue by oknozor** [oknozor/toml-bombadil#17]

**Comment by DSpeckhals** [comment]
Thanks for putting all of this together! I've been using it for a couple of days now vs. a home-grown symlink script before with great improvements.

I think I could work on the `unlink` subcommand. One question I have is around profiles. Currently, `link` can include profile arguments as well. Do you envision similar -- but reverse -- functionality for `unlink`, or should unlink just remove the targets for the default and all profiles?

**Comment by oknozor** [comment]
Thanks for your kind message ! 
 
I think for now a basic implementation would be nice : just unlink all existing linked dotfiles, regardless of the profile.
It might get messy if we try to make it too precise. One could just unlink, then (re) link the new profile.

Maybe it should output something like this : 
```
bombadil unlink
Removed symlink : 
   path/to/symlink/one
   path/to/symlink/two
Errored : 
  path/to/symlink/on/error
```
I have no strong opinion on the output format, as long as it is human readable. If you have something better in mind go ahead !
