### ISSUE TITLE
Bombadil should not stop processing dots because of one linking issue

### ISSUE THREAD

**Issue by lucas-dclrcq** [oknozor/toml-bombadil#19]
When there are multiple dots that bombadil cannot link, only the first error is shown to the user.

_Steps_

1. Create a file with two dots pointing to unexisting sources :

```
[[dot]]
source = "pouet"
target = ".config/pouet

[[dot]]
source = "pouet2"
target = ".config/pouet2
```
2. Run bombadil link command

3. The output only shows the first error :

```
Path does not exists : "/home/lucas/.dotfiles/.pouet"
```

_Current behavior :_

Bombadil show an error for the first problematic dot and stops processing dots

_Proposed behavior :_

bombadil should continue processing dots if there is an error.
so it can alert the user on other problematic dots (and also not break the user's system because of one problematic dot)

**Comment by oknozor** [comment]
I think this is related to unlink failing on orphan symlink (#16). Can you provide the steps reproduce ?

**Comment by oknozor** [comment]
#24

**Comment by oknozor** [comment]
Will be release in v2.0.0
