### ISSUE TITLE
Feature Request: Add possibility to encrypt secret vars using GPG

### ISSUE THREAD

**Issue by lucas-dclrcq** [oknozor/toml-bombadil#20]
Bombadil should support secrets for variables (example: user password in a maven setttings template) to avoid committing secret values in a dotfile repository.

Proposal :

_Creating secrets :_

Bombadil should have a command enabling an user to add a secret variable to a variable file. 

Ex: `bombadil add-secret --var-file path/to/var/file --var-name maven_password --value mypassword`

optionally --value could be replaced by the --ask parameter and bombadil should prompt the user for the secret value

_Encrypting/Decrypting_

Bombadil should inspire from pass (the standard unix password manager) and use gpg to encrypt/decrypt secret

Bombadil would delegate encrypting/decrypting to gpg, this simplify greatly the management of keys etc..

When bombadil needs to encrypt/unencrypt a variable it should use the default gpg key and eventually prompt the user for the gpg key passphrase  if needed.

**Comment by oknozor** [comment]
- [rpgp](https://crates.io/crates/pgp)
  - *pros* : pure rust implementation (no C runtime dependency)
  - *cons* : no file system (default key location etc) integration
 
- [gpgme](https://crates.io/crates/gpgme)
  - *pros* : high level binding to gpgme C lib
  - *cons* : depends on gpgme C library and its development files

**Comment by oknozor** [comment]
- implemented in 04d3a89baaebb69ab207556db7cda8c2df4dce39
- still needs to confirm this is working with pinentry (my gpg cong might be wrong) could you test this by cloning 
and checking out v2.0.0-rc ? ( you might need to change your config according to the readme )

**Comment by oknozor** [comment]
still needs to implement the following : 
```
bombadil show-secrets
```
```
bombadil remove-secret {key}
```

In the mean time this could still be done via `gpg`

**Comment by oknozor** [comment]
impletented in #35
