### ISSUE TITLE
[FEATURE] Way to disable rendering on specific files

### ISSUE THREAD

**Issue by amatrelan** [oknozor/toml-bombadil#262]
**Is your feature request related to a problem? Please describe.**

There is now little problem way the rendering works and there should be way to disable it on specific file.

I use `playerctl` to see media data in my song information and it needs in `--format` command output data to be wrapped in `{{status}}` so this causes problem with rendering how rendering is done.

**Describe the solution you'd like**

Way to disable Tera rendering on some specific files so this problem can be avoided.

**Describe alternatives you've considered**
There isn't really any workarounds right now, just bad edge case that can come when using specific tools.

**Additional context**
Full command I use to fetch metadata is `playerctl -a metadata --format {{status}} {{title}}`

**Comment by shaleh** [comment]
https://github.com/Keats/tera/issues/135
and specifically https://github.com/Keats/tera/issues/135#issuecomment-280820549

You can use the not so great `{{ "{{ foo }}" }}` syntax to escape braces.
