### ISSUE TITLE
[FEATURE] - Install completion at build time

### ISSUE THREAD

**Issue by oknozor** [oknozor/toml-bombadil#47]
#45 have been merged for now, but ultimately this should be done at build time and installed when packaging the application : 
see https://github.com/sharkdp/bat/blob/master/.github/workflows/CICD.yml

**Comment by svenstaro** [comment]
FYI in Arch I install them into the system like this: https://github.com/archlinux/svntogit-community/blob/1243f22ab98092f550c6a92015ecf12ef75d373b/trunk/PKGBUILD#L28
