### ISSUE TITLE
Disable Templating

### ISSUE THREAD

**Issue by eaxly** [oknozor/toml-bombadil#57]
Hey there 😺,
I've noticed that the README says, that Templating is optional. I am therefore guessing that it can be disabled. If that is the case, how?

Thank you for your help!

**Comment by oknozor** [comment]
Templating cannot be disabled. You can simply not use variables in your dotfiles to obtain that.  Bombadil will still symlink a copy of your dotfile though. 

I am planning to implement an option to directly symlink files without copy but it is not there yet. :)

**Comment by ExtinctAxolotl** [comment]
Alright, thank you for clarifying! Love this project so far keep the work up!💪
