### ISSUE TITLE
[BUG] When using --profile and bombadil toml configuration is not valid, the error is not explicit enough

### ISSUE THREAD

**Issue by lucas-dclrcq** [oknozor/toml-bombadil#62]
If my bombadil toml configuration file is not valid (eg: missing a comma in an array) and I use the link command with the profile parameter (eg: bombadil link --profiles test) the error is the following : 

```
error: 'test' isn't a valid value for '--profiles <profiles>...'
        [possible values: ]


USAGE:
    bombadil link --profiles <profiles>...

For more information try --help
```

The error should be about the toml file not being properly formatted and not about some unexisting profile.

**Comment by muchgitsuchwow** [comment]
The reason is in fact available via `bombadil get profiles`.
