### ISSUE TITLE
Create 2.0.1 release 

### ISSUE THREAD

**Issue by aeyoll** [oknozor/toml-bombadil#64]
Hello,
Can you create a new release, so this commit is taken into account please? https://github.com/oknozor/toml-bombadil/commit/42a7ff957adbaea2fbd4c4d150745ca34f18b93b (toml-bombadil can't be installed at the moment)
Thanks a lot

**Comment by oknozor** [comment]
@aeyoll thank you for pointing that out. 

Just created [2.1.0](https://github.com/oknozor/toml-bombadil/releases/tag/2.1.0), I was not aware the build was failing for 2.0.0 most of the time I am installing from my local repo or from the arch user repository so I didn't notice. 

I've been working on another project lately but will work on toml-bombadil again soon.

**Comment by aeyoll** [comment]
Thanks @oknozor!
