### ISSUE TITLE
[FEATURE] Consider symlinking every file individually when specifying a directory.

### ISSUE THREAD

**Issue by flyxi121** [oknozor/toml-bombadil#65]
**Is your feature request related to a problem? Please describe.**
Currently when you have multiple files which belong in a directory you just specify the directory, eg.
```
nvim = { source = "nvim", target = ".config/nvim" }
```

But there is a problem. Every time you call `bombadil link` it overwrites the files that neovim creates in the config directory (for example the plugin directory). That means that I have to specify every file and folder which should be linked into `.config/vim` individually so that it does not overwrite files and directories.

**Describe the solution you'd like**
I would like that bombadil takes every file in the directory `nvim` and symlinks it individually when I specify `nvim = { source = "nvim", target = ".config/nvim" }`.

**Describe alternatives you've considered**
I considered specifying every file individually, which makes writing the configuration file very tedious.

Of course if you know a way to do what I want without changing anything it would be awesome as well and thank you for this awesome Dotfile Manager!

**Comment by oknozor** [comment]
Hello @flyxi121

It might seems a good idea to get the directory tree and link only inner files but that would actually make your dotfiles harder to manage in my opinion. 

Toml-bombadil config has a declarative approach and we try to avoid hidden behaviors. In other word if your config states
the `nvim` directory links to `~/.config/nvim`, running `bombadil link` will do exactly this. Linking your dotfiles should not left your config in an inconsistent state.  

It is easy to forget what config files are present in your `~/.config` directories and spend hours figuring out what was left behind.

That said there are multiple ways you can solve this, here are how you could do it with vim-plug.

**1. use a post install hook:**
```toml
[settings]
# Runs vim-plug `PlugInstall` in headless mode and quit when finished
posthooks = [ "nvim --headless +PlugInstall +qa" ]
```

**2. Place your plugin directory somewhere not managed by toml-bombadil**
```vim
" init.vim
call plug#begin('~/.vim/plugged')
````

You might what to adapt this if you are using another plugin manager.

I would recommend using both methods to always get to the desired state running `bombadil link`.

**Comment by flyxi121** [comment]
Alright, I have to admit that never having hidden behavior is probably the best choice. Thanks for the tips to avoid the problem in the first place!
