### ISSUE TITLE
[BUG] doc bats-test HOWTO.md redirect to 404 pages

### ISSUE THREAD

**Issue by kakawait** [oknozor/toml-bombadil#68]
**To Reproduce**
1. Go to https://oknozor.github.io/toml-bombadil/docs/contributing/how-to-contribute/
2. Click on HOWTO

> Write bats tests
>
> If you have spotted a bug, a great way to help us improve toml bombadil is to write a bats test to reproduce it, see [HOWTO](https://oknozor.github.io/toml-bombadil/docs/contributing/how-to-contribute/bats-tests/HOWTO.md) for more info.

**Expected behavior**
Should render html version of https://github.com/oknozor/toml-bombadil/blob/main/bats-tests/HOWTO.md

**Additional context**
But since `bats-test` is outside `website` folder I don't know how to tell Zola taking the file in consideration.
Or update link to point to source (Github) directly

**Comment by oknozor** [comment]
@kakawait thank you for catching this, I guess just need to add an absolute link the [HOW TO](https://github.com/oknozor/toml-bombadil/blob/main/bats-tests/HOWTO.md) guide.
