### ISSUE TITLE
Improve contrast of doc's light version

### ISSUE THREAD

**Issue by kakawait** [oknozor/toml-bombadil#73]
In light mode the doc snippet code contrast has low ration that lead to be hard to read even more for colorblind people or other disease.

![Screen Shot 2022-01-04 at 14 19 52](https://user-images.githubusercontent.com/275609/148065266-2a6e2e54-4ec9-41cf-b8df-79ccec5488cf.png)

And lighthouse confirmed

<img width="839" alt="Screen Shot 2022-01-04 at 14 21 43" src="https://user-images.githubusercontent.com/275609/148065305-eb823a13-9958-4f12-a9b7-6c84cfb496c8.png">

Personally I don't have any eyes disease but even reading the doc in late night was a bit tiring. (A bit too late in night to find out the switch button on topbar to switch to dark, then was perfect in dark mode).

**Comment by oknozor** [comment]
fixed: https://oknozor.github.io/toml-bombadil/
