### ISSUE TITLE
Switch to Tempfile

### ISSUE THREAD

**Issue by Nukesor** [oknozor/toml-bombadil#79]
The [temp_testdir](https://github.com/la10736/temp_testdir) library hasn't received any updates since over two years.

There's a proper maintained library which supplies similar functionality called [tempfile](https://github.com/Stebalien/tempfile).

I also requested a deprecation notice of the original `temp_testdir` author.

It would probably be a good idea to migrate to tempfile in the long run.

**Comment by oknozor** [comment]
Actually I made a crate name [sealed_test](https://github.com/oknozor/sealed-test) a few month ago for an other project. There is still an issue with tests returning a result and using the `?` syntax but I think it would fit in bombadil test harness. I'll try it and see how it goes.

**Comment by Nukesor** [comment]
Uh nice. Good to know :)

Feel free to close this issue then!
