### ISSUE TITLE
Update git2-rs version once it's out

### ISSUE THREAD

**Issue by Nukesor** [oknozor/toml-bombadil#87]
Libgit2 released a new version `1.4` and the bindings currently break on systems that already migrated to that version.

`git2-rs` is planning to release a new version with the update to `v1.4`: https://github.com/rust-lang/git2-rs/pull/811

Once this is done, I'll create a PR that'll simply bumps the version :)

**Comment by oknozor** [comment]
That's a great idea, unfortunately the clone functionality is not ready yet on gitoxide (see: https://github.com/Byron/gitoxide/issues/303). But once it's ready it would be neat to switch to gitoxide :)
