### ISSUE TITLE
[FEATURE] Upgrade to clap v3 with declarative syntax

### ISSUE THREAD

**Issue by svenstaro** [oknozor/toml-bombadil#91]
clap v3 supports nice declarative typesafe syntax. See here for an example: https://github.com/svenstaro/miniserve/blob/67e96523872eb5e94c6b828fc8c2a87646c1c5b2/src/args.rs#L12

Not only does this make the tool safer to use but it should reduce code and also allow for easy use for clap_mangen in order to easily solve #14.

**Comment by oknozor** [comment]
I have almost finished this already. Did not push anything yet though. 
I probably get this done by the week-end.

**Comment by svenstaro** [comment]
@oknozor any update on this? :)
